# Generated by Django 3.2.5 on 2021-07-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcontent', '0001_initial'),
        ('ucontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.BooleanField(default=False)),
                ('peer_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcontent.peer_content')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ucontent.user_content')),
            ],
        ),
    ]
