# Generated by Django 3.2.5 on 2021-08-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontent', '0001_initial'),
        ('merge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='peer_post',
        ),
        migrations.AddField(
            model_name='content',
            name='peer_post',
            field=models.ManyToManyField(blank=True, to='pcontent.Peer_content'),
        ),
    ]
