# Generated by Django 3.2.5 on 2021-07-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ucontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('peer_name', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('post', models.TextField(max_length=300)),
                ('add_merge', models.BooleanField(default=False)),
                ('limit', models.IntegerField(default=0)),
                ('ucontent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='ucontent.user_content')),
            ],
        ),
    ]
